services:
  data-base-1:
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - ./db-init/data-base-1.sql:/docker-entrypoint-initdb.d/data-base-1.sql
      - /var/lib/postgresql/data
  data-base-2:
    image: postgres:17.2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - ./db-init/data-base-2.sql:/docker-entrypoint-initdb.d/data-base-2.sql
      - /var/lib/postgresql/data